version: 0.2

phases:

  build:
    commands:
      - dotnet restore LabManager/LabManager.csproj
      - dotnet build LabManager/LabManager.csproj
      - dotnet publish LabManager/LabManager.csproj -o ./staging/app
      - cp ./LabManager/aws-windows-deployment-manifest.json ./LabManager/staging/.
artifacts:
  files:
    - '**/*'
  base-directory: 'LabManager/staging'
